pipeline {
    agent {
        node {
                label 'master'
                customWorkspace '/home/mwenyan/projects'
        }
    }
    
    options {
        timeout(time: 1, unit: 'HOURS') 
        skipStagesAfterUnstable()
    }
    
    environment {
        FLOGO_HOME = '/home/mwenyan/flogo/2.9'
        APP = 'flight_blueeye_ingestion_txf'
        IMAGE_NAME = 'flight_blueeye_ingestion'
        TAG = 'v1.2'
        IMAGE = "${IMAGE_NAME}:${TAG}"
    }
    stages {
        stage('Unit Test') {
            steps {
               echo "run unit tests...."

                sh "funit test -e /home/mwenyan/base/engine-linux_amd64 -a ${APP}/flogo.json -d ${APP}/unittest"

                echo "run unit tests....done"
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'sed -i "s/Primary\\/Secondary/Primary_Secondary/g" ${APP}/flogo.json'
              
                sh 'echo "building app docker iamge..."'
                sh 'sudo docker build -f ${APP}/Dockerfile -t ${IMAGE} ${APP}' 
                
                sh 'echo "tagging docker iamge..."'
                sh 'sudo docker tag ${IMAGE} tibjetblueontainers.azurecr.io/${IMAGE}'
                
                sh 'echo "acr login server ${ACR_LOGINSERVER}"'
                
                withCredentials([usernamePassword(credentialsId: 'acr-credentials', passwordVariable: 'ACR_PWD', usernameVariable: 'ACR_USER')]) {
                    sh 'echo $ACR_USER'
                   
                    sh 'echo "logging acr..."'
                    sh 'sudo docker login -u $ACR_USER -p $ACR_PWD ${ACR_LOGINSERVER}'
                    
                    sh 'echo "pushing image to acr..."'
                    sh 'sudo docker push tibjetblueontainers.azurecr.io/${IMAGE}'
                }
            }
        }
        stage('Deploy to AKS') {
            steps {
              
               sh '''
                   echo "create/update configmap"
                   kubectl create configmap flight-blueeye-ingestion-configmap --from-env-file=${APP}/env.properties -o yaml --dry-run | kubectl apply -f -
               
                   echo "deploy app..."
                   kubectl apply -f ${APP}/app.yaml

               '''
            }
        }
    }
    post {
        always {
             
            junit allowEmptyResults: false, testResults: 'flight_blueeye_ingestion_txf/unittest/outputs/report.xml'
        }
    }
}
